name: Publish to Nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: '3.1.x'

      # Publish Amazon AWS S3
      - name: publish AWS version change
        id: publish_core_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Talegen.Storage.Net.Aws/Talegen.Storage.Net.Aws.csproj
          
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
